# Generated by Django 2.1 on 2018-08-24 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('role', models.CharField(blank=True, choices=[('a', 'ACTOR'), ('d', 'DIRECTOR'), ('t', 'TRANSLATOR')], max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('files_count', models.PositiveIntegerField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('char_count', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('files_count', models.PositiveIntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='robotron_app.Actor')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='robotron_app.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('role', models.CharField(blank=True, choices=[('a', 'ACTOR'), ('d', 'DIRECTOR'), ('t', 'TRANSLATOR')], max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('batch_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('files_count', models.PositiveIntegerField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('char_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('actor_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sfx_note', models.TextField(blank=True, null=True)),
                ('tc_note', models.TextField(blank=True, null=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='robotron_app.Director')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True)),
                ('hour', models.TimeField(blank=True, null=True)),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robotron_app.Batch')),
                ('character', models.ForeignKey(limit_choices_to={'batch': models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robotron_app.Batch')}, on_delete=django.db.models.deletion.PROTECT, to='robotron_app.Character')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='robotron_app.Director')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TranslationString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16, unique=True)),
                ('english', models.TextField(blank=True, null=True)),
                ('polish', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('role', models.CharField(blank=True, choices=[('a', 'ACTOR'), ('d', 'DIRECTOR'), ('t', 'TRANSLATOR')], max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='session',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='robotron_app.Translator'),
        ),
        migrations.AddField(
            model_name='project',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robotron_app.Studio'),
        ),
        migrations.AddField(
            model_name='batch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robotron_app.Project'),
        ),
    ]
