# Generated by Django 2.1 on 2018-08-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robotron_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='role',
        ),
        migrations.RemoveField(
            model_name='director',
            name='role',
        ),
        migrations.RemoveField(
            model_name='translator',
            name='role',
        ),
    ]
