# Generated by Django 2.1 on 2018-08-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotron_app', '0002_auto_20180824_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['surname']},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['surname']},
        ),
        migrations.AlterModelOptions(
            name='translator',
            options={'ordering': ['surname']},
        ),
        migrations.AddField(
            model_name='actor',
            name='surname',
            field=models.CharField(default='tmp', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='surname',
            field=models.CharField(default='tmp', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translator',
            name='surname',
            field=models.CharField(default='tmp', max_length=64),
            preserve_default=False,
        ),
    ]
