# Generated by Django 2.1 on 2018-09-01 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robotron_app', '0004_auto_20180901_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='session',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robotron_app.Character'),
        ),
    ]
