# Generated by Django 2.1 on 2018-09-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robotron_app', '0005_auto_20180901_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='translator',
            options={'ordering': ['name']},
        ),
    ]
