# Generated by Django 2.1 on 2018-09-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robotron_app', '0006_auto_20180902_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='director',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='translator',
            name='surname',
        ),
    ]
